### ISSUE TITLE
`run_launcher_server` command looks like it fails for podman, with `psutils` permission error

### ISSUE THREAD

**Issue by jmetz** [aicell-lab/hypha-launcher#4]
* triton-launcher version: 0.1.0
* Python version:  3.11.7
* Operating System: Linux x86_64

### Description

Trying to launch the server appears to fail even though it seems to run the pulling.

### What I Did

```
 python -m triton_launcher run_launcher_server
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 1714, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 2344, in connections
    ret = _connections.retrieve(kind, self.pid)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 1028, in retrieve 
    inodes = self.get_proc_inodes(pid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 849, in get_proc_inodes
    for fd in os.listdir("%s/%s/fd" % (self._procfs_path, pid)):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/521141/fd'
```

**Comment by jmetz** [comment]
Note: This is using `podman`, which continues to pull the `nvidia-triton` image after this error.

**Comment by jmetz** [comment]
BTW: this is the same issue : https://stackoverflow.com/questions/62118693/getting-psutil-accessdenied-pid-6836-error-using-psutil. Looks like you have to be `root`... probably better if we can avoid this in general? How did you avoid this issue on the `HPC` login node @Nanguage
